// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

/*
Package example is a generated protocol buffer package.

GoGo gRPC Example

This example is used to show how to use gRPC and
gRPC-Gateway with GoGo Protobuf.

It is generated from these files:
	example.proto

It has these top-level messages:
	User
	UserRole
	UpdateUserRequest
	ListUsersRequest
*/
package example

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/protobuf/types"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

import time "time"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *User) Validate() error {
	if !(this.ID > 0) {
		return go_proto_validators.FieldError("ID", fmt.Errorf(`ID must a positive integer`))
	}
	if this.CreateDate != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreateDate); err != nil {
			return go_proto_validators.FieldError("CreateDate", err)
		}
	}
	return nil
}
func (this *UserRole) Validate() error {
	return nil
}
func (this *UpdateUserRequest) Validate() error {
	if this.User != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return go_proto_validators.FieldError("User", err)
		}
	}
	if this.UpdateMask != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.UpdateMask); err != nil {
			return go_proto_validators.FieldError("UpdateMask", err)
		}
	}
	return nil
}
func (this *ListUsersRequest) Validate() error {
	if this.CreatedSince != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.CreatedSince); err != nil {
			return go_proto_validators.FieldError("CreatedSince", err)
		}
	}
	if this.OlderThan != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.OlderThan); err != nil {
			return go_proto_validators.FieldError("OlderThan", err)
		}
	}
	return nil
}
